<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="15" failures="9" disabled="0" errors="0" timestamp="2018-04-22T21:03:41" time="4.86" name="AllTests">
  <testsuite name="TestEnv_Reliable" tests="2" failures="2" disabled="0" errors="0" time="0.548">
    <testcase name="TestAccept_Backlog1" status="run" time="0.269" classname="TestEnv_Reliable">
      <failure message="testhandshake.cpp:82&#x0A;Value of: temp_addr.sin_family&#x0A;  Actual: 65384&#x0A;Expected: addr.sin_family&#x0A;Which is: 2" type=""><![CDATA[testhandshake.cpp:82
Value of: temp_addr.sin_family
  Actual: 65384
Expected: addr.sin_family
Which is: 2]]></failure>
      <failure message="testhandshake.cpp:83&#x0A;Value of: temp_addr.sin_port&#x0A;  Actual: 46973&#x0A;Expected: addr.sin_port&#x0A;Which is: 3879" type=""><![CDATA[testhandshake.cpp:83
Value of: temp_addr.sin_port
  Actual: 46973
Expected: addr.sin_port
Which is: 3879]]></failure>
      <failure message="testhandshake.cpp:90&#x0A;Value of: expected_accept&#x0A;  Actual: 3&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 1" type=""><![CDATA[testhandshake.cpp:90
Value of: expected_accept
  Actual: 3
Expected: (int)client_sockets.size()
Which is: 1]]></failure>
      <failure message="testhandshake.cpp:168&#x0A;Value of: expected_connect&#x0A;  Actual: 1&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 0" type=""><![CDATA[testhandshake.cpp:168
Value of: expected_connect
  Actual: 1
Expected: (int)client_sockets.size()
Which is: 0]]></failure>
      <failure message="testhandshake.cpp:168&#x0A;Value of: expected_connect&#x0A;  Actual: 1&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 0" type=""><![CDATA[testhandshake.cpp:168
Value of: expected_connect
  Actual: 1
Expected: (int)client_sockets.size()
Which is: 0]]></failure>
      <failure message="testhandshake.cpp:168&#x0A;Value of: expected_connect&#x0A;  Actual: 1&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 0" type=""><![CDATA[testhandshake.cpp:168
Value of: expected_connect
  Actual: 1
Expected: (int)client_sockets.size()
Which is: 0]]></failure>
    </testcase>
    <testcase name="TestAccept_Backlog2" status="run" time="0.279" classname="TestEnv_Reliable">
      <failure message="testhandshake.cpp:82&#x0A;Value of: temp_addr.sin_family&#x0A;  Actual: 11792&#x0A;Expected: addr.sin_family&#x0A;Which is: 2" type=""><![CDATA[testhandshake.cpp:82
Value of: temp_addr.sin_family
  Actual: 11792
Expected: addr.sin_family
Which is: 2]]></failure>
      <failure message="testhandshake.cpp:83&#x0A;Value of: temp_addr.sin_port&#x0A;  Actual: 11897&#x0A;Expected: addr.sin_port&#x0A;Which is: 3879" type=""><![CDATA[testhandshake.cpp:83
Value of: temp_addr.sin_port
  Actual: 11897
Expected: addr.sin_port
Which is: 3879]]></failure>
      <failure message="testhandshake.cpp:90&#x0A;Value of: expected_accept&#x0A;  Actual: 6&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 1" type=""><![CDATA[testhandshake.cpp:90
Value of: expected_accept
  Actual: 6
Expected: (int)client_sockets.size()
Which is: 1]]></failure>
      <failure message="testhandshake.cpp:168&#x0A;Value of: expected_connect&#x0A;  Actual: 1&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 0" type=""><![CDATA[testhandshake.cpp:168
Value of: expected_connect
  Actual: 1
Expected: (int)client_sockets.size()
Which is: 0]]></failure>
      <failure message="testhandshake.cpp:168&#x0A;Value of: expected_connect&#x0A;  Actual: 1&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 0" type=""><![CDATA[testhandshake.cpp:168
Value of: expected_connect
  Actual: 1
Expected: (int)client_sockets.size()
Which is: 0]]></failure>
      <failure message="testhandshake.cpp:168&#x0A;Value of: expected_connect&#x0A;  Actual: 1&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 0" type=""><![CDATA[testhandshake.cpp:168
Value of: expected_connect
  Actual: 1
Expected: (int)client_sockets.size()
Which is: 0]]></failure>
      <failure message="testhandshake.cpp:168&#x0A;Value of: expected_connect&#x0A;  Actual: 1&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 0" type=""><![CDATA[testhandshake.cpp:168
Value of: expected_connect
  Actual: 1
Expected: (int)client_sockets.size()
Which is: 0]]></failure>
      <failure message="testhandshake.cpp:168&#x0A;Value of: expected_connect&#x0A;  Actual: 1&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 0" type=""><![CDATA[testhandshake.cpp:168
Value of: expected_connect
  Actual: 1
Expected: (int)client_sockets.size()
Which is: 0]]></failure>
      <failure message="testhandshake.cpp:168&#x0A;Value of: expected_connect&#x0A;  Actual: 1&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 0" type=""><![CDATA[testhandshake.cpp:168
Value of: expected_connect
  Actual: 1
Expected: (int)client_sockets.size()
Which is: 0]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="TestEnv_Any" tests="13" failures="7" disabled="0" errors="0" time="4.309">
    <testcase name="TestAccept_BeforeAccept" status="run" time="0.485" classname="TestEnv_Any">
      <failure message="testhandshake.cpp:82&#x0A;Value of: temp_addr.sin_family&#x0A;  Actual: 11792&#x0A;Expected: addr.sin_family&#x0A;Which is: 2" type=""><![CDATA[testhandshake.cpp:82
Value of: temp_addr.sin_family
  Actual: 11792
Expected: addr.sin_family
Which is: 2]]></failure>
      <failure message="testhandshake.cpp:83&#x0A;Value of: temp_addr.sin_port&#x0A;  Actual: 11897&#x0A;Expected: addr.sin_port&#x0A;Which is: 3879" type=""><![CDATA[testhandshake.cpp:83
Value of: temp_addr.sin_port
  Actual: 11897
Expected: addr.sin_port
Which is: 3879]]></failure>
      <failure message="testhandshake.cpp:168&#x0A;Value of: expected_connect&#x0A;  Actual: 1&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 0" type=""><![CDATA[testhandshake.cpp:168
Value of: expected_connect
  Actual: 1
Expected: (int)client_sockets.size()
Which is: 0]]></failure>
    </testcase>
    <testcase name="TestAccept_AfterAccept" status="run" time="0.459" classname="TestEnv_Any">
      <failure message="testhandshake.cpp:82&#x0A;Value of: temp_addr.sin_family&#x0A;  Actual: 11792&#x0A;Expected: addr.sin_family&#x0A;Which is: 2" type=""><![CDATA[testhandshake.cpp:82
Value of: temp_addr.sin_family
  Actual: 11792
Expected: addr.sin_family
Which is: 2]]></failure>
      <failure message="testhandshake.cpp:83&#x0A;Value of: temp_addr.sin_port&#x0A;  Actual: 11897&#x0A;Expected: addr.sin_port&#x0A;Which is: 3879" type=""><![CDATA[testhandshake.cpp:83
Value of: temp_addr.sin_port
  Actual: 11897
Expected: addr.sin_port
Which is: 3879]]></failure>
      <failure message="testhandshake.cpp:168&#x0A;Value of: expected_connect&#x0A;  Actual: 1&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 0" type=""><![CDATA[testhandshake.cpp:168
Value of: expected_connect
  Actual: 1
Expected: (int)client_sockets.size()
Which is: 0]]></failure>
    </testcase>
    <testcase name="TestAccept_MultipleInterface1" status="run" time="0.936" classname="TestEnv_Any">
      <failure message="testhandshake.cpp:48&#x0A;Value of: 0&#x0A;Expected: ret&#x0A;Which is: -1" type=""><![CDATA[testhandshake.cpp:48
Value of: 0
Expected: ret
Which is: -1]]></failure>
      <failure message="testhandshake.cpp:81&#x0A;Value of: (addr.sin_addr.s_addr == 0) || (addr.sin_addr.s_addr == temp_addr.sin_addr.s_addr)&#x0A;  Actual: false&#x0A;Expected: true" type=""><![CDATA[testhandshake.cpp:81
Value of: (addr.sin_addr.s_addr == 0) || (addr.sin_addr.s_addr == temp_addr.sin_addr.s_addr)
  Actual: false
Expected: true]]></failure>
      <failure message="testhandshake.cpp:82&#x0A;Value of: temp_addr.sin_family&#x0A;  Actual: 11792&#x0A;Expected: addr.sin_family&#x0A;Which is: 2" type=""><![CDATA[testhandshake.cpp:82
Value of: temp_addr.sin_family
  Actual: 11792
Expected: addr.sin_family
Which is: 2]]></failure>
      <failure message="testhandshake.cpp:83&#x0A;Value of: temp_addr.sin_port&#x0A;  Actual: 11897&#x0A;Expected: addr.sin_port&#x0A;Which is: 3879" type=""><![CDATA[testhandshake.cpp:83
Value of: temp_addr.sin_port
  Actual: 11897
Expected: addr.sin_port
Which is: 3879]]></failure>
      <failure message="testhandshake.cpp:81&#x0A;Value of: (addr.sin_addr.s_addr == 0) || (addr.sin_addr.s_addr == temp_addr.sin_addr.s_addr)&#x0A;  Actual: false&#x0A;Expected: true" type=""><![CDATA[testhandshake.cpp:81
Value of: (addr.sin_addr.s_addr == 0) || (addr.sin_addr.s_addr == temp_addr.sin_addr.s_addr)
  Actual: false
Expected: true]]></failure>
      <failure message="testhandshake.cpp:82&#x0A;Value of: temp_addr.sin_family&#x0A;  Actual: 3600&#x0A;Expected: addr.sin_family&#x0A;Which is: 2" type=""><![CDATA[testhandshake.cpp:82
Value of: temp_addr.sin_family
  Actual: 3600
Expected: addr.sin_family
Which is: 2]]></failure>
      <failure message="testhandshake.cpp:83&#x0A;Value of: temp_addr.sin_port&#x0A;  Actual: 11641&#x0A;Expected: addr.sin_port&#x0A;Which is: 3879" type=""><![CDATA[testhandshake.cpp:83
Value of: temp_addr.sin_port
  Actual: 11641
Expected: addr.sin_port
Which is: 3879]]></failure>
      <failure message="testhandshake.cpp:90&#x0A;Value of: expected_accept&#x0A;  Actual: 5&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 1" type=""><![CDATA[testhandshake.cpp:90
Value of: expected_accept
  Actual: 5
Expected: (int)client_sockets.size()
Which is: 1]]></failure>
      <failure message="testhandshake.cpp:90&#x0A;Value of: expected_accept&#x0A;  Actual: 3&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 1" type=""><![CDATA[testhandshake.cpp:90
Value of: expected_accept
  Actual: 3
Expected: (int)client_sockets.size()
Which is: 1]]></failure>
      <failure message="testhandshake.cpp:168&#x0A;Value of: expected_connect&#x0A;  Actual: 5&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 0" type=""><![CDATA[testhandshake.cpp:168
Value of: expected_connect
  Actual: 5
Expected: (int)client_sockets.size()
Which is: 0]]></failure>
      <failure message="testhandshake.cpp:168&#x0A;Value of: expected_connect&#x0A;  Actual: 3&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 0" type=""><![CDATA[testhandshake.cpp:168
Value of: expected_connect
  Actual: 3
Expected: (int)client_sockets.size()
Which is: 0]]></failure>
    </testcase>
    <testcase name="TestAccept_MultipleInterface2" status="run" time="0.879" classname="TestEnv_Any">
      <failure message="testhandshake.cpp:48&#x0A;Value of: 0&#x0A;Expected: ret&#x0A;Which is: -1" type=""><![CDATA[testhandshake.cpp:48
Value of: 0
Expected: ret
Which is: -1]]></failure>
      <failure message="testhandshake.cpp:81&#x0A;Value of: (addr.sin_addr.s_addr == 0) || (addr.sin_addr.s_addr == temp_addr.sin_addr.s_addr)&#x0A;  Actual: false&#x0A;Expected: true" type=""><![CDATA[testhandshake.cpp:81
Value of: (addr.sin_addr.s_addr == 0) || (addr.sin_addr.s_addr == temp_addr.sin_addr.s_addr)
  Actual: false
Expected: true]]></failure>
      <failure message="testhandshake.cpp:82&#x0A;Value of: temp_addr.sin_family&#x0A;  Actual: 11792&#x0A;Expected: addr.sin_family&#x0A;Which is: 2" type=""><![CDATA[testhandshake.cpp:82
Value of: temp_addr.sin_family
  Actual: 11792
Expected: addr.sin_family
Which is: 2]]></failure>
      <failure message="testhandshake.cpp:83&#x0A;Value of: temp_addr.sin_port&#x0A;  Actual: 11897&#x0A;Expected: addr.sin_port&#x0A;Which is: 3879" type=""><![CDATA[testhandshake.cpp:83
Value of: temp_addr.sin_port
  Actual: 11897
Expected: addr.sin_port
Which is: 3879]]></failure>
      <failure message="testhandshake.cpp:81&#x0A;Value of: (addr.sin_addr.s_addr == 0) || (addr.sin_addr.s_addr == temp_addr.sin_addr.s_addr)&#x0A;  Actual: false&#x0A;Expected: true" type=""><![CDATA[testhandshake.cpp:81
Value of: (addr.sin_addr.s_addr == 0) || (addr.sin_addr.s_addr == temp_addr.sin_addr.s_addr)
  Actual: false
Expected: true]]></failure>
      <failure message="testhandshake.cpp:82&#x0A;Value of: temp_addr.sin_family&#x0A;  Actual: 7696&#x0A;Expected: addr.sin_family&#x0A;Which is: 2" type=""><![CDATA[testhandshake.cpp:82
Value of: temp_addr.sin_family
  Actual: 7696
Expected: addr.sin_family
Which is: 2]]></failure>
      <failure message="testhandshake.cpp:83&#x0A;Value of: temp_addr.sin_port&#x0A;  Actual: 11769&#x0A;Expected: addr.sin_port&#x0A;Which is: 3879" type=""><![CDATA[testhandshake.cpp:83
Value of: temp_addr.sin_port
  Actual: 11769
Expected: addr.sin_port
Which is: 3879]]></failure>
      <failure message="testhandshake.cpp:90&#x0A;Value of: expected_accept&#x0A;  Actual: 2&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 1" type=""><![CDATA[testhandshake.cpp:90
Value of: expected_accept
  Actual: 2
Expected: (int)client_sockets.size()
Which is: 1]]></failure>
      <failure message="testhandshake.cpp:90&#x0A;Value of: expected_accept&#x0A;  Actual: 4&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 1" type=""><![CDATA[testhandshake.cpp:90
Value of: expected_accept
  Actual: 4
Expected: (int)client_sockets.size()
Which is: 1]]></failure>
      <failure message="testhandshake.cpp:168&#x0A;Value of: expected_connect&#x0A;  Actual: 2&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 0" type=""><![CDATA[testhandshake.cpp:168
Value of: expected_connect
  Actual: 2
Expected: (int)client_sockets.size()
Which is: 0]]></failure>
      <failure message="testhandshake.cpp:168&#x0A;Value of: expected_connect&#x0A;  Actual: 4&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 0" type=""><![CDATA[testhandshake.cpp:168
Value of: expected_connect
  Actual: 4
Expected: (int)client_sockets.size()
Which is: 0]]></failure>
    </testcase>
    <testcase name="TestConnect_BeforeAccept" status="run" time="0.002" classname="TestEnv_Any" />
    <testcase name="TestConnect_AfterAccept" status="run" time="0.002" classname="TestEnv_Any" />
    <testcase name="TestConnect_SimultaneousConnect" status="run" time="0.001" classname="TestEnv_Any" />
    <testcase name="TestClose_Connect_CloseFirst" status="run" time="0.001" classname="TestEnv_Any" />
    <testcase name="TestClose_Connect_CloseLater" status="run" time="0.001" classname="TestEnv_Any" />
    <testcase name="TestClose_Connect_CloseSimultaneous" status="run" time="0.001" classname="TestEnv_Any" />
    <testcase name="TestClose_Accept_CloseLater" status="run" time="0.512" classname="TestEnv_Any">
      <failure message="testclose.cpp:75&#x0A;Value of: temp_addr.sin_family&#x0A;  Actual: 7696&#x0A;Expected: addr.sin_family&#x0A;Which is: 2" type=""><![CDATA[testclose.cpp:75
Value of: temp_addr.sin_family
  Actual: 7696
Expected: addr.sin_family
Which is: 2]]></failure>
      <failure message="testclose.cpp:76&#x0A;Value of: temp_addr.sin_port&#x0A;  Actual: 11769&#x0A;Expected: addr.sin_port&#x0A;Which is: 3879" type=""><![CDATA[testclose.cpp:76
Value of: temp_addr.sin_port
  Actual: 11769
Expected: addr.sin_port
Which is: 3879]]></failure>
      <failure message="testclose.cpp:122&#x0A;Expected: (ret) &gt;= (0), actual: -1 vs 0" type=""><![CDATA[testclose.cpp:122
Expected: (ret) >= (0), actual: -1 vs 0]]></failure>
      <failure message="testclose.cpp:127&#x0A;Value of: 0&#x0A;Expected: ret&#x0A;Which is: -1" type=""><![CDATA[testclose.cpp:127
Value of: 0
Expected: ret
Which is: -1]]></failure>
      <failure message="testclose.cpp:128&#x0A;Value of: temp_addr.sin_addr.s_addr&#x0A;  Actual: 32550&#x0A;Expected: addr.sin_addr.s_addr&#x0A;Which is: 117483712" type=""><![CDATA[testclose.cpp:128
Value of: temp_addr.sin_addr.s_addr
  Actual: 32550
Expected: addr.sin_addr.s_addr
Which is: 117483712]]></failure>
      <failure message="testclose.cpp:129&#x0A;Value of: temp_addr.sin_family&#x0A;  Actual: 11792&#x0A;Expected: addr.sin_family&#x0A;Which is: 2" type=""><![CDATA[testclose.cpp:129
Value of: temp_addr.sin_family
  Actual: 11792
Expected: addr.sin_family
Which is: 2]]></failure>
      <failure message="testclose.cpp:130&#x0A;Value of: temp_addr.sin_port&#x0A;  Actual: 11897&#x0A;Expected: addr.sin_port&#x0A;Which is: 3879" type=""><![CDATA[testclose.cpp:130
Value of: temp_addr.sin_port
  Actual: 11897
Expected: addr.sin_port
Which is: 3879]]></failure>
      <failure message="testclose.cpp:136&#x0A;Value of: 0&#x0A;Expected: ret&#x0A;Which is: -1" type=""><![CDATA[testclose.cpp:136
Value of: 0
Expected: ret
Which is: -1]]></failure>
      <failure message="testclose.cpp:139&#x0A;Expected: (sleep_time) &gt;= (0), actual: -140731975900128 vs 0" type=""><![CDATA[testclose.cpp:139
Expected: (sleep_time) >= (0), actual: -140731975900128 vs 0]]></failure>
    </testcase>
    <testcase name="TestClose_Accept_CloseFirst" status="run" time="0.515" classname="TestEnv_Any">
      <failure message="testclose.cpp:75&#x0A;Value of: temp_addr.sin_family&#x0A;  Actual: 11792&#x0A;Expected: addr.sin_family&#x0A;Which is: 2" type=""><![CDATA[testclose.cpp:75
Value of: temp_addr.sin_family
  Actual: 11792
Expected: addr.sin_family
Which is: 2]]></failure>
      <failure message="testclose.cpp:76&#x0A;Value of: temp_addr.sin_port&#x0A;  Actual: 11897&#x0A;Expected: addr.sin_port&#x0A;Which is: 3879" type=""><![CDATA[testclose.cpp:76
Value of: temp_addr.sin_port
  Actual: 11897
Expected: addr.sin_port
Which is: 3879]]></failure>
      <failure message="testclose.cpp:122&#x0A;Expected: (ret) &gt;= (0), actual: -1 vs 0" type=""><![CDATA[testclose.cpp:122
Expected: (ret) >= (0), actual: -1 vs 0]]></failure>
      <failure message="testclose.cpp:127&#x0A;Value of: 0&#x0A;Expected: ret&#x0A;Which is: -1" type=""><![CDATA[testclose.cpp:127
Value of: 0
Expected: ret
Which is: -1]]></failure>
      <failure message="testclose.cpp:128&#x0A;Value of: temp_addr.sin_addr.s_addr&#x0A;  Actual: 32550&#x0A;Expected: addr.sin_addr.s_addr&#x0A;Which is: 117483712" type=""><![CDATA[testclose.cpp:128
Value of: temp_addr.sin_addr.s_addr
  Actual: 32550
Expected: addr.sin_addr.s_addr
Which is: 117483712]]></failure>
      <failure message="testclose.cpp:129&#x0A;Value of: temp_addr.sin_family&#x0A;  Actual: 7696&#x0A;Expected: addr.sin_family&#x0A;Which is: 2" type=""><![CDATA[testclose.cpp:129
Value of: temp_addr.sin_family
  Actual: 7696
Expected: addr.sin_family
Which is: 2]]></failure>
      <failure message="testclose.cpp:130&#x0A;Value of: temp_addr.sin_port&#x0A;  Actual: 11769&#x0A;Expected: addr.sin_port&#x0A;Which is: 3879" type=""><![CDATA[testclose.cpp:130
Value of: temp_addr.sin_port
  Actual: 11769
Expected: addr.sin_port
Which is: 3879]]></failure>
      <failure message="testclose.cpp:136&#x0A;Value of: 0&#x0A;Expected: ret&#x0A;Which is: -1" type=""><![CDATA[testclose.cpp:136
Value of: 0
Expected: ret
Which is: -1]]></failure>
      <failure message="testclose.cpp:139&#x0A;Expected: (sleep_time) &gt;= (0), actual: -140731975890128 vs 0" type=""><![CDATA[testclose.cpp:139
Expected: (sleep_time) >= (0), actual: -140731975890128 vs 0]]></failure>
    </testcase>
    <testcase name="TestClose_Accept_CloseSimultaneous" status="run" time="0.511" classname="TestEnv_Any">
      <failure message="testclose.cpp:75&#x0A;Value of: temp_addr.sin_family&#x0A;  Actual: 7696&#x0A;Expected: addr.sin_family&#x0A;Which is: 2" type=""><![CDATA[testclose.cpp:75
Value of: temp_addr.sin_family
  Actual: 7696
Expected: addr.sin_family
Which is: 2]]></failure>
      <failure message="testclose.cpp:76&#x0A;Value of: temp_addr.sin_port&#x0A;  Actual: 11769&#x0A;Expected: addr.sin_port&#x0A;Which is: 3879" type=""><![CDATA[testclose.cpp:76
Value of: temp_addr.sin_port
  Actual: 11769
Expected: addr.sin_port
Which is: 3879]]></failure>
      <failure message="testclose.cpp:122&#x0A;Expected: (ret) &gt;= (0), actual: -1 vs 0" type=""><![CDATA[testclose.cpp:122
Expected: (ret) >= (0), actual: -1 vs 0]]></failure>
      <failure message="testclose.cpp:127&#x0A;Value of: 0&#x0A;Expected: ret&#x0A;Which is: -1" type=""><![CDATA[testclose.cpp:127
Value of: 0
Expected: ret
Which is: -1]]></failure>
      <failure message="testclose.cpp:128&#x0A;Value of: temp_addr.sin_addr.s_addr&#x0A;  Actual: 32550&#x0A;Expected: addr.sin_addr.s_addr&#x0A;Which is: 117483712" type=""><![CDATA[testclose.cpp:128
Value of: temp_addr.sin_addr.s_addr
  Actual: 32550
Expected: addr.sin_addr.s_addr
Which is: 117483712]]></failure>
      <failure message="testclose.cpp:129&#x0A;Value of: temp_addr.sin_family&#x0A;  Actual: 11792&#x0A;Expected: addr.sin_family&#x0A;Which is: 2" type=""><![CDATA[testclose.cpp:129
Value of: temp_addr.sin_family
  Actual: 11792
Expected: addr.sin_family
Which is: 2]]></failure>
      <failure message="testclose.cpp:130&#x0A;Value of: temp_addr.sin_port&#x0A;  Actual: 11897&#x0A;Expected: addr.sin_port&#x0A;Which is: 3879" type=""><![CDATA[testclose.cpp:130
Value of: temp_addr.sin_port
  Actual: 11897
Expected: addr.sin_port
Which is: 3879]]></failure>
      <failure message="testclose.cpp:136&#x0A;Value of: 0&#x0A;Expected: ret&#x0A;Which is: -1" type=""><![CDATA[testclose.cpp:136
Value of: 0
Expected: ret
Which is: -1]]></failure>
      <failure message="testclose.cpp:139&#x0A;Expected: (sleep_time) &gt;= (0), actual: -140731975900128 vs 0" type=""><![CDATA[testclose.cpp:139
Expected: (sleep_time) >= (0), actual: -140731975900128 vs 0]]></failure>
    </testcase>
  </testsuite>
</testsuites>
