<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="15" failures="3" disabled="0" errors="0" timestamp="2018-04-23T03:24:53" time="1.474" name="AllTests">
  <testsuite name="TestEnv_Reliable" tests="2" failures="1" disabled="0" errors="0" time="0.141">
    <testcase name="TestAccept_Backlog1" status="run" time="0.05" classname="TestEnv_Reliable" />
    <testcase name="TestAccept_Backlog2" status="run" time="0.09" classname="TestEnv_Reliable">
      <failure message="testhandshake.cpp:89&#x0A;Value of: expected_accept&#x0A;  Actual: 6&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 1" type=""><![CDATA[testhandshake.cpp:89
Value of: expected_accept
  Actual: 6
Expected: (int)client_sockets.size()
Which is: 1]]></failure>
      <failure message="testhandshake.cpp:167&#x0A;Value of: expected_connect&#x0A;  Actual: 1&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 0" type=""><![CDATA[testhandshake.cpp:167
Value of: expected_connect
  Actual: 1
Expected: (int)client_sockets.size()
Which is: 0]]></failure>
      <failure message="testhandshake.cpp:167&#x0A;Value of: expected_connect&#x0A;  Actual: 1&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 0" type=""><![CDATA[testhandshake.cpp:167
Value of: expected_connect
  Actual: 1
Expected: (int)client_sockets.size()
Which is: 0]]></failure>
      <failure message="testhandshake.cpp:167&#x0A;Value of: expected_connect&#x0A;  Actual: 1&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 0" type=""><![CDATA[testhandshake.cpp:167
Value of: expected_connect
  Actual: 1
Expected: (int)client_sockets.size()
Which is: 0]]></failure>
      <failure message="testhandshake.cpp:167&#x0A;Value of: expected_connect&#x0A;  Actual: 1&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 0" type=""><![CDATA[testhandshake.cpp:167
Value of: expected_connect
  Actual: 1
Expected: (int)client_sockets.size()
Which is: 0]]></failure>
      <failure message="testhandshake.cpp:167&#x0A;Value of: expected_connect&#x0A;  Actual: 1&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 0" type=""><![CDATA[testhandshake.cpp:167
Value of: expected_connect
  Actual: 1
Expected: (int)client_sockets.size()
Which is: 0]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="TestEnv_Any" tests="13" failures="2" disabled="0" errors="0" time="1.333">
    <testcase name="TestClose_Connect_CloseFirst" status="run" time="0.001" classname="TestEnv_Any" />
    <testcase name="TestClose_Connect_CloseLater" status="run" time="0.002" classname="TestEnv_Any" />
    <testcase name="TestClose_Connect_CloseSimultaneous" status="run" time="0.001" classname="TestEnv_Any" />
    <testcase name="TestClose_Accept_CloseLater" status="run" time="0.001" classname="TestEnv_Any" />
    <testcase name="TestClose_Accept_CloseFirst" status="run" time="0.001" classname="TestEnv_Any" />
    <testcase name="TestClose_Accept_CloseSimultaneous" status="run" time="0.001" classname="TestEnv_Any" />
    <testcase name="TestAccept_BeforeAccept" status="run" time="0.001" classname="TestEnv_Any" />
    <testcase name="TestAccept_AfterAccept" status="run" time="0.001" classname="TestEnv_Any" />
    <testcase name="TestAccept_MultipleInterface1" status="run" time="0.669" classname="TestEnv_Any">
      <failure message="testhandshake.cpp:89&#x0A;Value of: expected_accept&#x0A;  Actual: 5&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 1" type=""><![CDATA[testhandshake.cpp:89
Value of: expected_accept
  Actual: 5
Expected: (int)client_sockets.size()
Which is: 1]]></failure>
      <failure message="testhandshake.cpp:89&#x0A;Value of: expected_accept&#x0A;  Actual: 3&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 1" type=""><![CDATA[testhandshake.cpp:89
Value of: expected_accept
  Actual: 3
Expected: (int)client_sockets.size()
Which is: 1]]></failure>
      <failure message="testhandshake.cpp:167&#x0A;Value of: expected_connect&#x0A;  Actual: 5&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 1" type=""><![CDATA[testhandshake.cpp:167
Value of: expected_connect
  Actual: 5
Expected: (int)client_sockets.size()
Which is: 1]]></failure>
      <failure message="testhandshake.cpp:167&#x0A;Value of: expected_connect&#x0A;  Actual: 3&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 1" type=""><![CDATA[testhandshake.cpp:167
Value of: expected_connect
  Actual: 3
Expected: (int)client_sockets.size()
Which is: 1]]></failure>
    </testcase>
    <testcase name="TestAccept_MultipleInterface2" status="run" time="0.651" classname="TestEnv_Any">
      <failure message="testhandshake.cpp:89&#x0A;Value of: expected_accept&#x0A;  Actual: 2&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 1" type=""><![CDATA[testhandshake.cpp:89
Value of: expected_accept
  Actual: 2
Expected: (int)client_sockets.size()
Which is: 1]]></failure>
      <failure message="testhandshake.cpp:89&#x0A;Value of: expected_accept&#x0A;  Actual: 4&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 1" type=""><![CDATA[testhandshake.cpp:89
Value of: expected_accept
  Actual: 4
Expected: (int)client_sockets.size()
Which is: 1]]></failure>
      <failure message="testhandshake.cpp:167&#x0A;Value of: expected_connect&#x0A;  Actual: 2&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 1" type=""><![CDATA[testhandshake.cpp:167
Value of: expected_connect
  Actual: 2
Expected: (int)client_sockets.size()
Which is: 1]]></failure>
      <failure message="testhandshake.cpp:167&#x0A;Value of: expected_connect&#x0A;  Actual: 4&#x0A;Expected: (int)client_sockets.size()&#x0A;Which is: 1" type=""><![CDATA[testhandshake.cpp:167
Value of: expected_connect
  Actual: 4
Expected: (int)client_sockets.size()
Which is: 1]]></failure>
    </testcase>
    <testcase name="TestConnect_BeforeAccept" status="run" time="0.001" classname="TestEnv_Any" />
    <testcase name="TestConnect_AfterAccept" status="run" time="0.002" classname="TestEnv_Any" />
    <testcase name="TestConnect_SimultaneousConnect" status="run" time="0.001" classname="TestEnv_Any" />
  </testsuite>
</testsuites>
